### ISSUE TITLE
DevBlocks Missing Files

### ISSUE THREAD

**Issue by vivekchakraverty** [Manonox/godot-dev-blocks#2]
I cant use DevBlocks with my current Godot 4.3 project. Installation goes on smoothly but it shows unfound dependencies! The error just comes and goes so it is a bit hard even taking a screenshot of the same!

**Comment by Manonox** [comment]
I forgor to update the Godot Asset Library download commit hash

Type inference changed between 4.2-4.3, do this in the code:
https://github.com/Manonox/godot-dev-blocks/commit/a6a74768dab4fd7d146d1a01cf370fe4b58ff35b
(`addons/devblocks/blocks/basic_block.gd`)

If that doesn't fix the error, record a clip or something
